AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.0

Style/BarePercentLiterals:
  EnforcedStyle: percent_q
Style/ClassAndModuleChildren:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrivialAccessors:
  AllowPredicates: true

# Need discussion
Style/AndOr:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SpaceAfterComma:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/BlockEndNewline:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/CommandLiteral:
  Enabled: false

# Needs refactors
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/PredicateName:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
