name: Capistrano
highlighter: pygments
safe: true
lsi: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
table_of_contents:
  dirs: [documentation]
exclude: ["Gemfile", "Gemfile.lock", "README.md"]
